name: Laravel CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PHP_VERSION: '8.4'
  DB_CONNECTION: sqlite
  DB_DATABASE: database/database.sqlite
  COMPOSER_CACHE_DIR: ~/.composer/cache

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite
          coverage: none

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup application environment
        run: |
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          php artisan key:generate
          chmod -R 777 storage bootstrap/cache

      - name: Install dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Setup test database
        run: |
          mkdir -p database
          touch ${{ env.DB_DATABASE }}

      - name: Execute tests
        env:
          DB_CONNECTION: ${{ env.DB_CONNECTION }}
          DB_DATABASE: ${{ env.DB_DATABASE }}
        run: php artisan test
